title: Course Intros
description: Course introduction pages
baseurl: "course-intros/"
url: ""
future: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
